/* automatically generated by rust-bindgen 0.63.0 */

#[repr(u32)]
#[doc = "  @brief AON DCDC level type definition"]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum AON_DCDC_LEVEL_Type {
    #[doc = "< AON DCDC voltage 0.900V"]
    AON_DCDC_LEVEL_0P900V = 0,
    #[doc = "< AON DCDC voltage 1.075V"]
    AON_DCDC_LEVEL_1P075V = 7,
    #[doc = "< AON DCDC voltage 1.100V"]
    AON_DCDC_LEVEL_1P100V = 8,
    #[doc = "< AON DCDC voltage 1.125V"]
    AON_DCDC_LEVEL_1P125V = 9,
    #[doc = "< AON DCDC voltage 1.900V"]
    AON_DCDC_LEVEL_1P900V = 31,
}
